#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    drupal-boilerplate-web-80-http:
      entrypoints:
        - http-18080
      rule: HostRegexp(`^drupal-boilerplate\.ddev\.site$`)
      
      service: "drupal-boilerplate-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "drupal-boilerplate-redirectHttps"
    drupal-boilerplate-web-8025-http:
      entrypoints:
        - http-18025
      rule: HostRegexp(`^drupal-boilerplate\.ddev\.site$`)
      
      service: "drupal-boilerplate-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "drupal-boilerplate-redirectHttps"
    drupal-boilerplate-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^drupal-boilerplate\.ddev\.site$`)
      
      service: "drupal-boilerplate-xhgui-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "drupal-boilerplate-redirectHttps"
    
    
    
    drupal-boilerplate-web-80-https:
      entrypoints:
        - http-14443
      rule: HostRegexp(`^drupal-boilerplate\.ddev\.site$`)
      
      service: "drupal-boilerplate-web-80"
      ruleSyntax: v3
      
      tls: true
      
    drupal-boilerplate-web-8025-https:
      entrypoints:
        - http-18026
      rule: HostRegexp(`^drupal-boilerplate\.ddev\.site$`)
      
      service: "drupal-boilerplate-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    
    drupal-boilerplate-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^drupal-boilerplate\.ddev\.site$`)
      
      service: "drupal-boilerplate-xhgui-80"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    drupal-boilerplate-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    drupal-boilerplate-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-drupal-boilerplate-web:80
        
    drupal-boilerplate-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-drupal-boilerplate-web:8025
        
    
    
    drupal-boilerplate-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-drupal-boilerplate-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/drupal-boilerplate.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/drupal-boilerplate.key